/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.api;

import com.cashful.ApiException;
import com.cashful.model.BadRequestResponseDto;
import java.math.BigDecimal;
import com.cashful.model.ConfirmPaymentIntentDto;
import com.cashful.model.ConfirmPaymentIntentResponseDto;
import com.cashful.model.CreatePaymentIntentDto;
import com.cashful.model.InternalServerErrorResponseDto;
import com.cashful.model.ListPaymentIntentsResponseDto;
import com.cashful.model.NotFoundResponseDto;
import com.cashful.model.PaymentIntentResponseDto;
import com.cashful.model.UnauthorizedResponseDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentIntentsApi
 */
@Disabled
public class PaymentIntentsApiTest {

    private final PaymentIntentsApi api = new PaymentIntentsApi();

    /**
     * Cancel Payment Intent
     *
     * Cancels a payment intent that has not yet succeeded or failed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelPaymentIntentTest() throws ApiException {
        String id = null;
        PaymentIntentResponseDto response = api.cancelPaymentIntent(id);
        // TODO: test validations
    }

    /**
     * Confirm Payment Intent
     *
     * Confirms a payment intent that requires confirmation and returns 3DS parameters for card authentication.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void confirmPaymentIntentTest() throws ApiException {
        String id = null;
        ConfirmPaymentIntentDto confirmPaymentIntentDto = null;
        ConfirmPaymentIntentResponseDto response = api.confirmPaymentIntent(id, confirmPaymentIntentDto);
        // TODO: test validations
    }

    /**
     * Create Payment Intent
     *
     * Creates a payment intent for a payment attempt. Used for hosted checkout or direct integrations.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPaymentIntentTest() throws ApiException {
        CreatePaymentIntentDto createPaymentIntentDto = null;
        PaymentIntentResponseDto response = api.createPaymentIntent(createPaymentIntentDto);
        // TODO: test validations
    }

    /**
     * List Payment Intents
     *
     * Lists payment intents for a specific merchant with pagination and filtering.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPaymentIntentsTest() throws ApiException {
        String merchantId = null;
        BigDecimal limit = null;
        BigDecimal offset = null;
        String status = null;
        ListPaymentIntentsResponseDto response = api.listPaymentIntents(merchantId, limit, offset, status);
        // TODO: test validations
    }

    /**
     * Retrieve Payment Intent
     *
     * Retrieves the current state of a specific payment intent.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrievePaymentIntentTest() throws ApiException {
        String id = null;
        PaymentIntentResponseDto response = api.retrievePaymentIntent(id);
        // TODO: test validations
    }

}
