/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.api;

import com.cashful.ApiException;
import java.math.BigDecimal;
import com.cashful.model.CreateProductDto;
import com.cashful.model.ErrorResponseDto;
import com.cashful.model.ListProductsResponseDto;
import com.cashful.model.ProductResponseDto;
import com.cashful.model.UpdateProductDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Create Product
     *
     * Defines a product in the merchant&#39;s catalog (e.g., \&quot;Airtime,\&quot; \&quot;Data\&quot;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProductTest() throws ApiException {
        CreateProductDto createProductDto = null;
        ProductResponseDto response = api.createProduct(createProductDto);
        // TODO: test validations
    }

    /**
     * List Products
     *
     * Retrieves all products in the merchant&#39;s catalog.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProductsTest() throws ApiException {
        BigDecimal limit = null;
        BigDecimal offset = null;
        String merchantId = null;
        Boolean active = null;
        ListProductsResponseDto response = api.listProducts(limit, offset, merchantId, active);
        // TODO: test validations
    }

    /**
     * Retrieve Product
     *
     * Retrieves a single product by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveProductTest() throws ApiException {
        String id = null;
        ProductResponseDto response = api.retrieveProduct(id);
        // TODO: test validations
    }

    /**
     * Update Product
     *
     * Updates a product&#39;s name, description, or metadata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProductTest() throws ApiException {
        String id = null;
        UpdateProductDto updateProductDto = null;
        ProductResponseDto response = api.updateProduct(id, updateProductDto);
        // TODO: test validations
    }

}
