/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.api;

import com.cashful.ApiException;
import java.math.BigDecimal;
import com.cashful.model.ConfirmUploadDto;
import com.cashful.model.ErrorResponseDto;
import com.cashful.model.FileDto;
import com.cashful.model.ListFilesResponseDto;
import com.cashful.model.PresignedDownloadResponseDto;
import com.cashful.model.PresignedUploadResponseDto;
import com.cashful.model.RequestUploadUrlDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StorageApi
 */
@Disabled
public class StorageApiTest {

    private final StorageApi api = new StorageApi();

    /**
     * Confirm that a file upload was completed
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerConfirmUploadCanaryTest() throws ApiException {
        ConfirmUploadDto confirmUploadDto = null;
        FileDto response = api.storageControllerConfirmUploadCanary(confirmUploadDto);
        // TODO: test validations
    }

    /**
     * Delete a file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerDeleteCanaryTest() throws ApiException {
        String id = null;
        api.storageControllerDeleteCanary(id);
        // TODO: test validations
    }

    /**
     * Get a presigned download URL for a file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerGetDownloadUrlCanaryTest() throws ApiException {
        String id = null;
        PresignedDownloadResponseDto response = api.storageControllerGetDownloadUrlCanary(id);
        // TODO: test validations
    }

    /**
     * List files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerListCanaryTest() throws ApiException {
        String merchantId = null;
        BigDecimal limit = null;
        BigDecimal offset = null;
        String tag = null;
        String status = null;
        String relatedEntityId = null;
        String relatedEntityType = null;
        ListFilesResponseDto response = api.storageControllerListCanary(merchantId, limit, offset, tag, status, relatedEntityId, relatedEntityType);
        // TODO: test validations
    }

    /**
     * Request a presigned URL for file upload
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerRequestUploadUrlCanaryTest() throws ApiException {
        RequestUploadUrlDto requestUploadUrlDto = null;
        PresignedUploadResponseDto response = api.storageControllerRequestUploadUrlCanary(requestUploadUrlDto);
        // TODO: test validations
    }

    /**
     * Get file details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storageControllerRetrieveCanaryTest() throws ApiException {
        String id = null;
        FileDto response = api.storageControllerRetrieveCanary(id);
        // TODO: test validations
    }

}
