/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.api;

import com.cashful.ApiException;
import com.cashful.model.BadRequestResponseDto;
import java.math.BigDecimal;
import com.cashful.model.CreateWebhookEndpointDto;
import com.cashful.model.InternalServerErrorResponseDto;
import com.cashful.model.ListWebhookEndpointsResponseDto;
import com.cashful.model.NotFoundResponseDto;
import com.cashful.model.UnauthorizedResponseDto;
import com.cashful.model.WebhookEndpointResponseDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Disabled
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    /**
     * Create Webhook Endpoint
     *
     * Registers a URL to receive real-time events (e.g., checkout.session.completed, purchase.succeeded).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWebhookEndpointTest() throws ApiException {
        CreateWebhookEndpointDto createWebhookEndpointDto = null;
        WebhookEndpointResponseDto response = api.createWebhookEndpoint(createWebhookEndpointDto);
        // TODO: test validations
    }

    /**
     * Delete Webhook Endpoint
     *
     * Stops sending events to a specific URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWebhookEndpointTest() throws ApiException {
        String id = null;
        Object response = api.deleteWebhookEndpoint(id);
        // TODO: test validations
    }

    /**
     * List Webhook Endpoints
     *
     * Lists all configured webhook endpoints.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWebhookEndpointsTest() throws ApiException {
        String merchantId = null;
        BigDecimal limit = null;
        BigDecimal offset = null;
        ListWebhookEndpointsResponseDto response = api.listWebhookEndpoints(merchantId, limit, offset);
        // TODO: test validations
    }

}
