/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import java.util.Objects;
import java.util.Locale;
import com.cashful.model.PaymentIntentResponseDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.cashful.JSON;

/**
 * ConfirmPaymentIntentResponseDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ConfirmPaymentIntentResponseDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PAYMENT_INTENT = "paymentIntent";
  @SerializedName(SERIALIZED_NAME_PAYMENT_INTENT)
  @javax.annotation.Nonnull
  private PaymentIntentResponseDto paymentIntent;

  public static final String SERIALIZED_NAME_IVERI_PARAMS = "iveriParams";
  @SerializedName(SERIALIZED_NAME_IVERI_PARAMS)
  @javax.annotation.Nullable
  private Object iveriParams;

  public static final String SERIALIZED_NAME_I_VERI3DS_ENDPOINT = "iVeri3dsEndpoint";
  @SerializedName(SERIALIZED_NAME_I_VERI3DS_ENDPOINT)
  @javax.annotation.Nullable
  private String iVeri3dsEndpoint;

  public static final String SERIALIZED_NAME_SANDBOX_MODE = "sandboxMode";
  @SerializedName(SERIALIZED_NAME_SANDBOX_MODE)
  @javax.annotation.Nullable
  private Boolean sandboxMode;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    SUCCEEDED("succeeded"),
    
    FAILED("failed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nullable
  private String transactionId;

  public static final String SERIALIZED_NAME_AUTH_CODE = "authCode";
  @SerializedName(SERIALIZED_NAME_AUTH_CODE)
  @javax.annotation.Nullable
  private String authCode;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private String reason;

  public ConfirmPaymentIntentResponseDto() {
  }

  public ConfirmPaymentIntentResponseDto paymentIntent(@javax.annotation.Nonnull PaymentIntentResponseDto paymentIntent) {
    this.paymentIntent = paymentIntent;
    return this;
  }

  /**
   * Get paymentIntent
   * @return paymentIntent
   */
  @javax.annotation.Nonnull
  public PaymentIntentResponseDto getPaymentIntent() {
    return paymentIntent;
  }

  public void setPaymentIntent(@javax.annotation.Nonnull PaymentIntentResponseDto paymentIntent) {
    this.paymentIntent = paymentIntent;
  }


  public ConfirmPaymentIntentResponseDto iveriParams(@javax.annotation.Nullable Object iveriParams) {
    this.iveriParams = iveriParams;
    return this;
  }

  /**
   * Get iveriParams
   * @return iveriParams
   */
  @javax.annotation.Nullable
  public Object getIveriParams() {
    return iveriParams;
  }

  public void setIveriParams(@javax.annotation.Nullable Object iveriParams) {
    this.iveriParams = iveriParams;
  }


  public ConfirmPaymentIntentResponseDto iVeri3dsEndpoint(@javax.annotation.Nullable String iVeri3dsEndpoint) {
    this.iVeri3dsEndpoint = iVeri3dsEndpoint;
    return this;
  }

  /**
   * Get iVeri3dsEndpoint
   * @return iVeri3dsEndpoint
   */
  @javax.annotation.Nullable
  public String getiVeri3dsEndpoint() {
    return iVeri3dsEndpoint;
  }

  public void setiVeri3dsEndpoint(@javax.annotation.Nullable String iVeri3dsEndpoint) {
    this.iVeri3dsEndpoint = iVeri3dsEndpoint;
  }


  public ConfirmPaymentIntentResponseDto sandboxMode(@javax.annotation.Nullable Boolean sandboxMode) {
    this.sandboxMode = sandboxMode;
    return this;
  }

  /**
   * Get sandboxMode
   * @return sandboxMode
   */
  @javax.annotation.Nullable
  public Boolean getSandboxMode() {
    return sandboxMode;
  }

  public void setSandboxMode(@javax.annotation.Nullable Boolean sandboxMode) {
    this.sandboxMode = sandboxMode;
  }


  public ConfirmPaymentIntentResponseDto status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public ConfirmPaymentIntentResponseDto transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public ConfirmPaymentIntentResponseDto authCode(@javax.annotation.Nullable String authCode) {
    this.authCode = authCode;
    return this;
  }

  /**
   * Get authCode
   * @return authCode
   */
  @javax.annotation.Nullable
  public String getAuthCode() {
    return authCode;
  }

  public void setAuthCode(@javax.annotation.Nullable String authCode) {
    this.authCode = authCode;
  }


  public ConfirmPaymentIntentResponseDto amount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nullable
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
  }


  public ConfirmPaymentIntentResponseDto currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public ConfirmPaymentIntentResponseDto reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmPaymentIntentResponseDto confirmPaymentIntentResponseDto = (ConfirmPaymentIntentResponseDto) o;
    return Objects.equals(this.paymentIntent, confirmPaymentIntentResponseDto.paymentIntent) &&
        Objects.equals(this.iveriParams, confirmPaymentIntentResponseDto.iveriParams) &&
        Objects.equals(this.iVeri3dsEndpoint, confirmPaymentIntentResponseDto.iVeri3dsEndpoint) &&
        Objects.equals(this.sandboxMode, confirmPaymentIntentResponseDto.sandboxMode) &&
        Objects.equals(this.status, confirmPaymentIntentResponseDto.status) &&
        Objects.equals(this.transactionId, confirmPaymentIntentResponseDto.transactionId) &&
        Objects.equals(this.authCode, confirmPaymentIntentResponseDto.authCode) &&
        Objects.equals(this.amount, confirmPaymentIntentResponseDto.amount) &&
        Objects.equals(this.currency, confirmPaymentIntentResponseDto.currency) &&
        Objects.equals(this.reason, confirmPaymentIntentResponseDto.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentIntent, iveriParams, iVeri3dsEndpoint, sandboxMode, status, transactionId, authCode, amount, currency, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmPaymentIntentResponseDto {\n");
    sb.append("    paymentIntent: ").append(toIndentedString(paymentIntent)).append("\n");
    sb.append("    iveriParams: ").append(toIndentedString(iveriParams)).append("\n");
    sb.append("    iVeri3dsEndpoint: ").append(toIndentedString(iVeri3dsEndpoint)).append("\n");
    sb.append("    sandboxMode: ").append(toIndentedString(sandboxMode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    authCode: ").append(toIndentedString(authCode)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("paymentIntent", "iveriParams", "iVeri3dsEndpoint", "sandboxMode", "status", "transactionId", "authCode", "amount", "currency", "reason"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("paymentIntent"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfirmPaymentIntentResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfirmPaymentIntentResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ConfirmPaymentIntentResponseDto is not found in the empty JSON string", ConfirmPaymentIntentResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfirmPaymentIntentResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConfirmPaymentIntentResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConfirmPaymentIntentResponseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `paymentIntent`
      PaymentIntentResponseDto.validateJsonElement(jsonObj.get("paymentIntent"));
      if ((jsonObj.get("iVeri3dsEndpoint") != null && !jsonObj.get("iVeri3dsEndpoint").isJsonNull()) && !jsonObj.get("iVeri3dsEndpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `iVeri3dsEndpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iVeri3dsEndpoint").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("transactionId") != null && !jsonObj.get("transactionId").isJsonNull()) && !jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if ((jsonObj.get("authCode") != null && !jsonObj.get("authCode").isJsonNull()) && !jsonObj.get("authCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `authCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authCode").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfirmPaymentIntentResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfirmPaymentIntentResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfirmPaymentIntentResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfirmPaymentIntentResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfirmPaymentIntentResponseDto>() {
           @Override
           public void write(JsonWriter out, ConfirmPaymentIntentResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfirmPaymentIntentResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfirmPaymentIntentResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfirmPaymentIntentResponseDto
   * @throws IOException if the JSON string is invalid with respect to ConfirmPaymentIntentResponseDto
   */
  public static ConfirmPaymentIntentResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfirmPaymentIntentResponseDto.class);
  }

  /**
   * Convert an instance of ConfirmPaymentIntentResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

