/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.cashful.JSON;

/**
 * CreateEventDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateEventDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchantId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  @javax.annotation.Nonnull
  private String merchantId;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nonnull
  private Object data;

  public static final String SERIALIZED_NAME_RELATED_ENTITY_ID = "relatedEntityId";
  @SerializedName(SERIALIZED_NAME_RELATED_ENTITY_ID)
  @javax.annotation.Nullable
  private String relatedEntityId;

  public static final String SERIALIZED_NAME_RELATED_ENTITY_TYPE = "relatedEntityType";
  @SerializedName(SERIALIZED_NAME_RELATED_ENTITY_TYPE)
  @javax.annotation.Nullable
  private String relatedEntityType;

  public CreateEventDto() {
  }

  public CreateEventDto merchantId(@javax.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

  /**
   * Merchant ID associated with the event
   * @return merchantId
   */
  @javax.annotation.Nonnull
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(@javax.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }


  public CreateEventDto type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Event type identifier (e.g., &#39;checkout.loaded&#39;)
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public CreateEventDto data(@javax.annotation.Nonnull Object data) {
    this.data = data;
    return this;
  }

  /**
   * Event payload data
   * @return data
   */
  @javax.annotation.Nonnull
  public Object getData() {
    return data;
  }

  public void setData(@javax.annotation.Nonnull Object data) {
    this.data = data;
  }


  public CreateEventDto relatedEntityId(@javax.annotation.Nullable String relatedEntityId) {
    this.relatedEntityId = relatedEntityId;
    return this;
  }

  /**
   * ID of the related entity
   * @return relatedEntityId
   */
  @javax.annotation.Nullable
  public String getRelatedEntityId() {
    return relatedEntityId;
  }

  public void setRelatedEntityId(@javax.annotation.Nullable String relatedEntityId) {
    this.relatedEntityId = relatedEntityId;
  }


  public CreateEventDto relatedEntityType(@javax.annotation.Nullable String relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
    return this;
  }

  /**
   * Type of the related entity
   * @return relatedEntityType
   */
  @javax.annotation.Nullable
  public String getRelatedEntityType() {
    return relatedEntityType;
  }

  public void setRelatedEntityType(@javax.annotation.Nullable String relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEventDto createEventDto = (CreateEventDto) o;
    return Objects.equals(this.merchantId, createEventDto.merchantId) &&
        Objects.equals(this.type, createEventDto.type) &&
        Objects.equals(this.data, createEventDto.data) &&
        Objects.equals(this.relatedEntityId, createEventDto.relatedEntityId) &&
        Objects.equals(this.relatedEntityType, createEventDto.relatedEntityType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, type, data, relatedEntityId, relatedEntityType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEventDto {\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    relatedEntityId: ").append(toIndentedString(relatedEntityId)).append("\n");
    sb.append("    relatedEntityType: ").append(toIndentedString(relatedEntityType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("merchantId", "type", "data", "relatedEntityId", "relatedEntityType"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("merchantId", "type", "data"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateEventDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateEventDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CreateEventDto is not found in the empty JSON string", CreateEventDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateEventDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateEventDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateEventDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("merchantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `merchantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantId").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("relatedEntityId") != null && !jsonObj.get("relatedEntityId").isJsonNull()) && !jsonObj.get("relatedEntityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `relatedEntityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relatedEntityId").toString()));
      }
      if ((jsonObj.get("relatedEntityType") != null && !jsonObj.get("relatedEntityType").isJsonNull()) && !jsonObj.get("relatedEntityType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `relatedEntityType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relatedEntityType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateEventDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateEventDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateEventDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateEventDto.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateEventDto>() {
           @Override
           public void write(JsonWriter out, CreateEventDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateEventDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateEventDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateEventDto
   * @throws IOException if the JSON string is invalid with respect to CreateEventDto
   */
  public static CreateEventDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateEventDto.class);
  }

  /**
   * Convert an instance of CreateEventDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

