/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.cashful.JSON;

/**
 * CustomerStatsDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CustomerStatsDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_DAILY = "daily";
  @SerializedName(SERIALIZED_NAME_DAILY)
  @javax.annotation.Nonnull
  private BigDecimal daily;

  public static final String SERIALIZED_NAME_WEEKLY = "weekly";
  @SerializedName(SERIALIZED_NAME_WEEKLY)
  @javax.annotation.Nonnull
  private BigDecimal weekly;

  public static final String SERIALIZED_NAME_MONTHLY = "monthly";
  @SerializedName(SERIALIZED_NAME_MONTHLY)
  @javax.annotation.Nonnull
  private BigDecimal monthly;

  public CustomerStatsDto() {
  }

  public CustomerStatsDto daily(@javax.annotation.Nonnull BigDecimal daily) {
    this.daily = daily;
    return this;
  }

  /**
   * New customers in the last 24 hours
   * @return daily
   */
  @javax.annotation.Nonnull
  public BigDecimal getDaily() {
    return daily;
  }

  public void setDaily(@javax.annotation.Nonnull BigDecimal daily) {
    this.daily = daily;
  }


  public CustomerStatsDto weekly(@javax.annotation.Nonnull BigDecimal weekly) {
    this.weekly = weekly;
    return this;
  }

  /**
   * New customers in the last 7 days
   * @return weekly
   */
  @javax.annotation.Nonnull
  public BigDecimal getWeekly() {
    return weekly;
  }

  public void setWeekly(@javax.annotation.Nonnull BigDecimal weekly) {
    this.weekly = weekly;
  }


  public CustomerStatsDto monthly(@javax.annotation.Nonnull BigDecimal monthly) {
    this.monthly = monthly;
    return this;
  }

  /**
   * New customers in the last 30 days
   * @return monthly
   */
  @javax.annotation.Nonnull
  public BigDecimal getMonthly() {
    return monthly;
  }

  public void setMonthly(@javax.annotation.Nonnull BigDecimal monthly) {
    this.monthly = monthly;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerStatsDto customerStatsDto = (CustomerStatsDto) o;
    return Objects.equals(this.daily, customerStatsDto.daily) &&
        Objects.equals(this.weekly, customerStatsDto.weekly) &&
        Objects.equals(this.monthly, customerStatsDto.monthly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daily, weekly, monthly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerStatsDto {\n");
    sb.append("    daily: ").append(toIndentedString(daily)).append("\n");
    sb.append("    weekly: ").append(toIndentedString(weekly)).append("\n");
    sb.append("    monthly: ").append(toIndentedString(monthly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("daily", "weekly", "monthly"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("daily", "weekly", "monthly"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomerStatsDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomerStatsDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CustomerStatsDto is not found in the empty JSON string", CustomerStatsDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomerStatsDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CustomerStatsDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomerStatsDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerStatsDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerStatsDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerStatsDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerStatsDto.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerStatsDto>() {
           @Override
           public void write(JsonWriter out, CustomerStatsDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerStatsDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomerStatsDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomerStatsDto
   * @throws IOException if the JSON string is invalid with respect to CustomerStatsDto
   */
  public static CustomerStatsDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerStatsDto.class);
  }

  /**
   * Convert an instance of CustomerStatsDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

