/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.cashful.JSON;

/**
 * OrganizationComplianceResponseDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class OrganizationComplianceResponseDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_DELETED_AT = "deletedAt";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organizationId";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  @javax.annotation.Nonnull
  private String organizationId;

  public static final String SERIALIZED_NAME_COMPANY_REGISTRATION_NAME = "companyRegistrationName";
  @SerializedName(SERIALIZED_NAME_COMPANY_REGISTRATION_NAME)
  @javax.annotation.Nullable
  private String companyRegistrationName;

  public static final String SERIALIZED_NAME_COMPANY_REGISTRATION_NUMBER = "companyRegistrationNumber";
  @SerializedName(SERIALIZED_NAME_COMPANY_REGISTRATION_NUMBER)
  @javax.annotation.Nullable
  private String companyRegistrationNumber;

  public static final String SERIALIZED_NAME_COMPANY_TRADING_NAME = "companyTradingName";
  @SerializedName(SERIALIZED_NAME_COMPANY_TRADING_NAME)
  @javax.annotation.Nullable
  private String companyTradingName;

  public static final String SERIALIZED_NAME_VAT_REGISTRATION_NUMBER = "vatRegistrationNumber";
  @SerializedName(SERIALIZED_NAME_VAT_REGISTRATION_NUMBER)
  @javax.annotation.Nullable
  private String vatRegistrationNumber;

  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  @javax.annotation.Nullable
  private String industry;

  public static final String SERIALIZED_NAME_SUB_INDUSTRY = "subIndustry";
  @SerializedName(SERIALIZED_NAME_SUB_INDUSTRY)
  @javax.annotation.Nullable
  private String subIndustry;

  public static final String SERIALIZED_NAME_ESTIMATED_ANNUAL_TURNOVER = "estimatedAnnualTurnover";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_ANNUAL_TURNOVER)
  @javax.annotation.Nullable
  private String estimatedAnnualTurnover;

  public static final String SERIALIZED_NAME_BUSINESS_DESCRIPTION = "businessDescription";
  @SerializedName(SERIALIZED_NAME_BUSINESS_DESCRIPTION)
  @javax.annotation.Nullable
  private String businessDescription;

  public static final String SERIALIZED_NAME_COMPANY_MOBILE_MONEY_SETTLEMENT_NUMBER = "companyMobileMoneySettlementNumber";
  @SerializedName(SERIALIZED_NAME_COMPANY_MOBILE_MONEY_SETTLEMENT_NUMBER)
  @javax.annotation.Nullable
  private String companyMobileMoneySettlementNumber;

  public static final String SERIALIZED_NAME_COMPANY_EMAIL = "companyEmail";
  @SerializedName(SERIALIZED_NAME_COMPANY_EMAIL)
  @javax.annotation.Nullable
  private String companyEmail;

  public static final String SERIALIZED_NAME_COMPANY_CONTACT_NUMBER = "companyContactNumber";
  @SerializedName(SERIALIZED_NAME_COMPANY_CONTACT_NUMBER)
  @javax.annotation.Nullable
  private String companyContactNumber;

  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  @javax.annotation.Nullable
  private String website;

  public static final String SERIALIZED_NAME_SOCIAL_MEDIA = "socialMedia";
  @SerializedName(SERIALIZED_NAME_SOCIAL_MEDIA)
  @javax.annotation.Nullable
  private String socialMedia;

  public static final String SERIALIZED_NAME_ACCOUNT_CONTACT_NUMBER = "accountContactNumber";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_CONTACT_NUMBER)
  @javax.annotation.Nullable
  private String accountContactNumber;

  public static final String SERIALIZED_NAME_CUSTOMER_SUPPORT_CONTACT_NUMBER = "customerSupportContactNumber";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_SUPPORT_CONTACT_NUMBER)
  @javax.annotation.Nullable
  private String customerSupportContactNumber;

  public static final String SERIALIZED_NAME_CUSTOMER_SUPPORT_ESCALATION_CONTACT_NUMBER = "customerSupportEscalationContactNumber";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_SUPPORT_ESCALATION_CONTACT_NUMBER)
  @javax.annotation.Nullable
  private String customerSupportEscalationContactNumber;

  public static final String SERIALIZED_NAME_EMERGENCY_CONTACT_NUMBER = "emergencyContactNumber";
  @SerializedName(SERIALIZED_NAME_EMERGENCY_CONTACT_NUMBER)
  @javax.annotation.Nullable
  private String emergencyContactNumber;

  public static final String SERIALIZED_NAME_STREET_ADDRESS = "streetAddress";
  @SerializedName(SERIALIZED_NAME_STREET_ADDRESS)
  @javax.annotation.Nullable
  private String streetAddress;

  public static final String SERIALIZED_NAME_APARTMENT = "apartment";
  @SerializedName(SERIALIZED_NAME_APARTMENT)
  @javax.annotation.Nullable
  private String apartment;

  public static final String SERIALIZED_NAME_SUBURB = "suburb";
  @SerializedName(SERIALIZED_NAME_SUBURB)
  @javax.annotation.Nullable
  private String suburb;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  @javax.annotation.Nullable
  private String city;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  @javax.annotation.Nullable
  private String postalCode;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_BANK = "bank";
  @SerializedName(SERIALIZED_NAME_BANK)
  @javax.annotation.Nullable
  private String bank;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPE = "accountType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE)
  @javax.annotation.Nullable
  private String accountType;

  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "accountName";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  @javax.annotation.Nullable
  private String accountName;

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBER = "accountNumber";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBER)
  @javax.annotation.Nullable
  private String accountNumber;

  public static final String SERIALIZED_NAME_BRANCH_CODE = "branchCode";
  @SerializedName(SERIALIZED_NAME_BRANCH_CODE)
  @javax.annotation.Nullable
  private String branchCode;

  public static final String SERIALIZED_NAME_SWIFT_CODE = "swiftCode";
  @SerializedName(SERIALIZED_NAME_SWIFT_CODE)
  @javax.annotation.Nullable
  private String swiftCode;

  public static final String SERIALIZED_NAME_CERTIFICATE_OF_INCORPORATION = "certificateOfIncorporation";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_OF_INCORPORATION)
  @javax.annotation.Nullable
  private String certificateOfIncorporation;

  public static final String SERIALIZED_NAME_IDENTITY_DOCUMENTS = "identityDocuments";
  @SerializedName(SERIALIZED_NAME_IDENTITY_DOCUMENTS)
  @javax.annotation.Nullable
  private String identityDocuments;

  public static final String SERIALIZED_NAME_BANK_ACCOUNT_CONFIRMATION_LETTER = "bankAccountConfirmationLetter";
  @SerializedName(SERIALIZED_NAME_BANK_ACCOUNT_CONFIRMATION_LETTER)
  @javax.annotation.Nullable
  private String bankAccountConfirmationLetter;

  public static final String SERIALIZED_NAME_PROOF_OF_BUSINESS_ADDRESS = "proofOfBusinessAddress";
  @SerializedName(SERIALIZED_NAME_PROOF_OF_BUSINESS_ADDRESS)
  @javax.annotation.Nullable
  private String proofOfBusinessAddress;

  public static final String SERIALIZED_NAME_TERMS_ACCEPTED = "termsAccepted";
  @SerializedName(SERIALIZED_NAME_TERMS_ACCEPTED)
  @javax.annotation.Nullable
  private Boolean termsAccepted;

  public static final String SERIALIZED_NAME_ACCEPTED_AT = "acceptedAt";
  @SerializedName(SERIALIZED_NAME_ACCEPTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime acceptedAt;

  /**
   * Gets or Sets currentStep
   */
  @JsonAdapter(CurrentStepEnum.Adapter.class)
  public enum CurrentStepEnum {
    INITIATION("initiation"),
    
    VERIFICATION("verification"),
    
    BUSINESS_DETAILS("business_details"),
    
    BANKING_DETAILS("banking_details"),
    
    UPLOAD_DOCUMENTS("upload_documents"),
    
    SIGN_AGREEMENT("sign_agreement");

    private String value;

    CurrentStepEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrentStepEnum fromValue(String value) {
      for (CurrentStepEnum b : CurrentStepEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrentStepEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrentStepEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrentStepEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrentStepEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CurrentStepEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CURRENT_STEP = "currentStep";
  @SerializedName(SERIALIZED_NAME_CURRENT_STEP)
  @javax.annotation.Nullable
  private CurrentStepEnum currentStep;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("pending"),
    
    VERIFIED("verified"),
    
    REJECTED("rejected");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_IS_COMPLETED = "isCompleted";
  @SerializedName(SERIALIZED_NAME_IS_COMPLETED)
  @javax.annotation.Nullable
  private Boolean isCompleted;

  public static final String SERIALIZED_NAME_COMPLETION_SCORE = "completionScore";
  @SerializedName(SERIALIZED_NAME_COMPLETION_SCORE)
  @javax.annotation.Nullable
  private BigDecimal completionScore;

  public OrganizationComplianceResponseDto() {
  }

  public OrganizationComplianceResponseDto id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public OrganizationComplianceResponseDto createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public OrganizationComplianceResponseDto updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public OrganizationComplianceResponseDto deletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public OrganizationComplianceResponseDto organizationId(@javax.annotation.Nonnull String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

  /**
   * Get organizationId
   * @return organizationId
   */
  @javax.annotation.Nonnull
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(@javax.annotation.Nonnull String organizationId) {
    this.organizationId = organizationId;
  }


  public OrganizationComplianceResponseDto companyRegistrationName(@javax.annotation.Nullable String companyRegistrationName) {
    this.companyRegistrationName = companyRegistrationName;
    return this;
  }

  /**
   * Get companyRegistrationName
   * @return companyRegistrationName
   */
  @javax.annotation.Nullable
  public String getCompanyRegistrationName() {
    return companyRegistrationName;
  }

  public void setCompanyRegistrationName(@javax.annotation.Nullable String companyRegistrationName) {
    this.companyRegistrationName = companyRegistrationName;
  }


  public OrganizationComplianceResponseDto companyRegistrationNumber(@javax.annotation.Nullable String companyRegistrationNumber) {
    this.companyRegistrationNumber = companyRegistrationNumber;
    return this;
  }

  /**
   * Get companyRegistrationNumber
   * @return companyRegistrationNumber
   */
  @javax.annotation.Nullable
  public String getCompanyRegistrationNumber() {
    return companyRegistrationNumber;
  }

  public void setCompanyRegistrationNumber(@javax.annotation.Nullable String companyRegistrationNumber) {
    this.companyRegistrationNumber = companyRegistrationNumber;
  }


  public OrganizationComplianceResponseDto companyTradingName(@javax.annotation.Nullable String companyTradingName) {
    this.companyTradingName = companyTradingName;
    return this;
  }

  /**
   * Get companyTradingName
   * @return companyTradingName
   */
  @javax.annotation.Nullable
  public String getCompanyTradingName() {
    return companyTradingName;
  }

  public void setCompanyTradingName(@javax.annotation.Nullable String companyTradingName) {
    this.companyTradingName = companyTradingName;
  }


  public OrganizationComplianceResponseDto vatRegistrationNumber(@javax.annotation.Nullable String vatRegistrationNumber) {
    this.vatRegistrationNumber = vatRegistrationNumber;
    return this;
  }

  /**
   * Get vatRegistrationNumber
   * @return vatRegistrationNumber
   */
  @javax.annotation.Nullable
  public String getVatRegistrationNumber() {
    return vatRegistrationNumber;
  }

  public void setVatRegistrationNumber(@javax.annotation.Nullable String vatRegistrationNumber) {
    this.vatRegistrationNumber = vatRegistrationNumber;
  }


  public OrganizationComplianceResponseDto industry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
    return this;
  }

  /**
   * Get industry
   * @return industry
   */
  @javax.annotation.Nullable
  public String getIndustry() {
    return industry;
  }

  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }


  public OrganizationComplianceResponseDto subIndustry(@javax.annotation.Nullable String subIndustry) {
    this.subIndustry = subIndustry;
    return this;
  }

  /**
   * Get subIndustry
   * @return subIndustry
   */
  @javax.annotation.Nullable
  public String getSubIndustry() {
    return subIndustry;
  }

  public void setSubIndustry(@javax.annotation.Nullable String subIndustry) {
    this.subIndustry = subIndustry;
  }


  public OrganizationComplianceResponseDto estimatedAnnualTurnover(@javax.annotation.Nullable String estimatedAnnualTurnover) {
    this.estimatedAnnualTurnover = estimatedAnnualTurnover;
    return this;
  }

  /**
   * Get estimatedAnnualTurnover
   * @return estimatedAnnualTurnover
   */
  @javax.annotation.Nullable
  public String getEstimatedAnnualTurnover() {
    return estimatedAnnualTurnover;
  }

  public void setEstimatedAnnualTurnover(@javax.annotation.Nullable String estimatedAnnualTurnover) {
    this.estimatedAnnualTurnover = estimatedAnnualTurnover;
  }


  public OrganizationComplianceResponseDto businessDescription(@javax.annotation.Nullable String businessDescription) {
    this.businessDescription = businessDescription;
    return this;
  }

  /**
   * Get businessDescription
   * @return businessDescription
   */
  @javax.annotation.Nullable
  public String getBusinessDescription() {
    return businessDescription;
  }

  public void setBusinessDescription(@javax.annotation.Nullable String businessDescription) {
    this.businessDescription = businessDescription;
  }


  public OrganizationComplianceResponseDto companyMobileMoneySettlementNumber(@javax.annotation.Nullable String companyMobileMoneySettlementNumber) {
    this.companyMobileMoneySettlementNumber = companyMobileMoneySettlementNumber;
    return this;
  }

  /**
   * Get companyMobileMoneySettlementNumber
   * @return companyMobileMoneySettlementNumber
   */
  @javax.annotation.Nullable
  public String getCompanyMobileMoneySettlementNumber() {
    return companyMobileMoneySettlementNumber;
  }

  public void setCompanyMobileMoneySettlementNumber(@javax.annotation.Nullable String companyMobileMoneySettlementNumber) {
    this.companyMobileMoneySettlementNumber = companyMobileMoneySettlementNumber;
  }


  public OrganizationComplianceResponseDto companyEmail(@javax.annotation.Nullable String companyEmail) {
    this.companyEmail = companyEmail;
    return this;
  }

  /**
   * Get companyEmail
   * @return companyEmail
   */
  @javax.annotation.Nullable
  public String getCompanyEmail() {
    return companyEmail;
  }

  public void setCompanyEmail(@javax.annotation.Nullable String companyEmail) {
    this.companyEmail = companyEmail;
  }


  public OrganizationComplianceResponseDto companyContactNumber(@javax.annotation.Nullable String companyContactNumber) {
    this.companyContactNumber = companyContactNumber;
    return this;
  }

  /**
   * Get companyContactNumber
   * @return companyContactNumber
   */
  @javax.annotation.Nullable
  public String getCompanyContactNumber() {
    return companyContactNumber;
  }

  public void setCompanyContactNumber(@javax.annotation.Nullable String companyContactNumber) {
    this.companyContactNumber = companyContactNumber;
  }


  public OrganizationComplianceResponseDto website(@javax.annotation.Nullable String website) {
    this.website = website;
    return this;
  }

  /**
   * Get website
   * @return website
   */
  @javax.annotation.Nullable
  public String getWebsite() {
    return website;
  }

  public void setWebsite(@javax.annotation.Nullable String website) {
    this.website = website;
  }


  public OrganizationComplianceResponseDto socialMedia(@javax.annotation.Nullable String socialMedia) {
    this.socialMedia = socialMedia;
    return this;
  }

  /**
   * Get socialMedia
   * @return socialMedia
   */
  @javax.annotation.Nullable
  public String getSocialMedia() {
    return socialMedia;
  }

  public void setSocialMedia(@javax.annotation.Nullable String socialMedia) {
    this.socialMedia = socialMedia;
  }


  public OrganizationComplianceResponseDto accountContactNumber(@javax.annotation.Nullable String accountContactNumber) {
    this.accountContactNumber = accountContactNumber;
    return this;
  }

  /**
   * Get accountContactNumber
   * @return accountContactNumber
   */
  @javax.annotation.Nullable
  public String getAccountContactNumber() {
    return accountContactNumber;
  }

  public void setAccountContactNumber(@javax.annotation.Nullable String accountContactNumber) {
    this.accountContactNumber = accountContactNumber;
  }


  public OrganizationComplianceResponseDto customerSupportContactNumber(@javax.annotation.Nullable String customerSupportContactNumber) {
    this.customerSupportContactNumber = customerSupportContactNumber;
    return this;
  }

  /**
   * Get customerSupportContactNumber
   * @return customerSupportContactNumber
   */
  @javax.annotation.Nullable
  public String getCustomerSupportContactNumber() {
    return customerSupportContactNumber;
  }

  public void setCustomerSupportContactNumber(@javax.annotation.Nullable String customerSupportContactNumber) {
    this.customerSupportContactNumber = customerSupportContactNumber;
  }


  public OrganizationComplianceResponseDto customerSupportEscalationContactNumber(@javax.annotation.Nullable String customerSupportEscalationContactNumber) {
    this.customerSupportEscalationContactNumber = customerSupportEscalationContactNumber;
    return this;
  }

  /**
   * Get customerSupportEscalationContactNumber
   * @return customerSupportEscalationContactNumber
   */
  @javax.annotation.Nullable
  public String getCustomerSupportEscalationContactNumber() {
    return customerSupportEscalationContactNumber;
  }

  public void setCustomerSupportEscalationContactNumber(@javax.annotation.Nullable String customerSupportEscalationContactNumber) {
    this.customerSupportEscalationContactNumber = customerSupportEscalationContactNumber;
  }


  public OrganizationComplianceResponseDto emergencyContactNumber(@javax.annotation.Nullable String emergencyContactNumber) {
    this.emergencyContactNumber = emergencyContactNumber;
    return this;
  }

  /**
   * Get emergencyContactNumber
   * @return emergencyContactNumber
   */
  @javax.annotation.Nullable
  public String getEmergencyContactNumber() {
    return emergencyContactNumber;
  }

  public void setEmergencyContactNumber(@javax.annotation.Nullable String emergencyContactNumber) {
    this.emergencyContactNumber = emergencyContactNumber;
  }


  public OrganizationComplianceResponseDto streetAddress(@javax.annotation.Nullable String streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

  /**
   * Get streetAddress
   * @return streetAddress
   */
  @javax.annotation.Nullable
  public String getStreetAddress() {
    return streetAddress;
  }

  public void setStreetAddress(@javax.annotation.Nullable String streetAddress) {
    this.streetAddress = streetAddress;
  }


  public OrganizationComplianceResponseDto apartment(@javax.annotation.Nullable String apartment) {
    this.apartment = apartment;
    return this;
  }

  /**
   * Get apartment
   * @return apartment
   */
  @javax.annotation.Nullable
  public String getApartment() {
    return apartment;
  }

  public void setApartment(@javax.annotation.Nullable String apartment) {
    this.apartment = apartment;
  }


  public OrganizationComplianceResponseDto suburb(@javax.annotation.Nullable String suburb) {
    this.suburb = suburb;
    return this;
  }

  /**
   * Get suburb
   * @return suburb
   */
  @javax.annotation.Nullable
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(@javax.annotation.Nullable String suburb) {
    this.suburb = suburb;
  }


  public OrganizationComplianceResponseDto city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @javax.annotation.Nullable
  public String getCity() {
    return city;
  }

  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public OrganizationComplianceResponseDto postalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Get postalCode
   * @return postalCode
   */
  @javax.annotation.Nullable
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
  }


  public OrganizationComplianceResponseDto country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public OrganizationComplianceResponseDto bank(@javax.annotation.Nullable String bank) {
    this.bank = bank;
    return this;
  }

  /**
   * Get bank
   * @return bank
   */
  @javax.annotation.Nullable
  public String getBank() {
    return bank;
  }

  public void setBank(@javax.annotation.Nullable String bank) {
    this.bank = bank;
  }


  public OrganizationComplianceResponseDto accountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
    return this;
  }

  /**
   * Get accountType
   * @return accountType
   */
  @javax.annotation.Nullable
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
  }


  public OrganizationComplianceResponseDto accountName(@javax.annotation.Nullable String accountName) {
    this.accountName = accountName;
    return this;
  }

  /**
   * Get accountName
   * @return accountName
   */
  @javax.annotation.Nullable
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(@javax.annotation.Nullable String accountName) {
    this.accountName = accountName;
  }


  public OrganizationComplianceResponseDto accountNumber(@javax.annotation.Nullable String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

  /**
   * Get accountNumber
   * @return accountNumber
   */
  @javax.annotation.Nullable
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(@javax.annotation.Nullable String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public OrganizationComplianceResponseDto branchCode(@javax.annotation.Nullable String branchCode) {
    this.branchCode = branchCode;
    return this;
  }

  /**
   * Get branchCode
   * @return branchCode
   */
  @javax.annotation.Nullable
  public String getBranchCode() {
    return branchCode;
  }

  public void setBranchCode(@javax.annotation.Nullable String branchCode) {
    this.branchCode = branchCode;
  }


  public OrganizationComplianceResponseDto swiftCode(@javax.annotation.Nullable String swiftCode) {
    this.swiftCode = swiftCode;
    return this;
  }

  /**
   * Get swiftCode
   * @return swiftCode
   */
  @javax.annotation.Nullable
  public String getSwiftCode() {
    return swiftCode;
  }

  public void setSwiftCode(@javax.annotation.Nullable String swiftCode) {
    this.swiftCode = swiftCode;
  }


  public OrganizationComplianceResponseDto certificateOfIncorporation(@javax.annotation.Nullable String certificateOfIncorporation) {
    this.certificateOfIncorporation = certificateOfIncorporation;
    return this;
  }

  /**
   * Get certificateOfIncorporation
   * @return certificateOfIncorporation
   */
  @javax.annotation.Nullable
  public String getCertificateOfIncorporation() {
    return certificateOfIncorporation;
  }

  public void setCertificateOfIncorporation(@javax.annotation.Nullable String certificateOfIncorporation) {
    this.certificateOfIncorporation = certificateOfIncorporation;
  }


  public OrganizationComplianceResponseDto identityDocuments(@javax.annotation.Nullable String identityDocuments) {
    this.identityDocuments = identityDocuments;
    return this;
  }

  /**
   * Get identityDocuments
   * @return identityDocuments
   */
  @javax.annotation.Nullable
  public String getIdentityDocuments() {
    return identityDocuments;
  }

  public void setIdentityDocuments(@javax.annotation.Nullable String identityDocuments) {
    this.identityDocuments = identityDocuments;
  }


  public OrganizationComplianceResponseDto bankAccountConfirmationLetter(@javax.annotation.Nullable String bankAccountConfirmationLetter) {
    this.bankAccountConfirmationLetter = bankAccountConfirmationLetter;
    return this;
  }

  /**
   * Get bankAccountConfirmationLetter
   * @return bankAccountConfirmationLetter
   */
  @javax.annotation.Nullable
  public String getBankAccountConfirmationLetter() {
    return bankAccountConfirmationLetter;
  }

  public void setBankAccountConfirmationLetter(@javax.annotation.Nullable String bankAccountConfirmationLetter) {
    this.bankAccountConfirmationLetter = bankAccountConfirmationLetter;
  }


  public OrganizationComplianceResponseDto proofOfBusinessAddress(@javax.annotation.Nullable String proofOfBusinessAddress) {
    this.proofOfBusinessAddress = proofOfBusinessAddress;
    return this;
  }

  /**
   * Get proofOfBusinessAddress
   * @return proofOfBusinessAddress
   */
  @javax.annotation.Nullable
  public String getProofOfBusinessAddress() {
    return proofOfBusinessAddress;
  }

  public void setProofOfBusinessAddress(@javax.annotation.Nullable String proofOfBusinessAddress) {
    this.proofOfBusinessAddress = proofOfBusinessAddress;
  }


  public OrganizationComplianceResponseDto termsAccepted(@javax.annotation.Nullable Boolean termsAccepted) {
    this.termsAccepted = termsAccepted;
    return this;
  }

  /**
   * Get termsAccepted
   * @return termsAccepted
   */
  @javax.annotation.Nullable
  public Boolean getTermsAccepted() {
    return termsAccepted;
  }

  public void setTermsAccepted(@javax.annotation.Nullable Boolean termsAccepted) {
    this.termsAccepted = termsAccepted;
  }


  public OrganizationComplianceResponseDto acceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
    return this;
  }

  /**
   * Get acceptedAt
   * @return acceptedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getAcceptedAt() {
    return acceptedAt;
  }

  public void setAcceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
  }


  public OrganizationComplianceResponseDto currentStep(@javax.annotation.Nullable CurrentStepEnum currentStep) {
    this.currentStep = currentStep;
    return this;
  }

  /**
   * Get currentStep
   * @return currentStep
   */
  @javax.annotation.Nullable
  public CurrentStepEnum getCurrentStep() {
    return currentStep;
  }

  public void setCurrentStep(@javax.annotation.Nullable CurrentStepEnum currentStep) {
    this.currentStep = currentStep;
  }


  public OrganizationComplianceResponseDto status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public OrganizationComplianceResponseDto isCompleted(@javax.annotation.Nullable Boolean isCompleted) {
    this.isCompleted = isCompleted;
    return this;
  }

  /**
   * Get isCompleted
   * @return isCompleted
   */
  @javax.annotation.Nullable
  public Boolean getIsCompleted() {
    return isCompleted;
  }

  public void setIsCompleted(@javax.annotation.Nullable Boolean isCompleted) {
    this.isCompleted = isCompleted;
  }


  public OrganizationComplianceResponseDto completionScore(@javax.annotation.Nullable BigDecimal completionScore) {
    this.completionScore = completionScore;
    return this;
  }

  /**
   * Get completionScore
   * @return completionScore
   */
  @javax.annotation.Nullable
  public BigDecimal getCompletionScore() {
    return completionScore;
  }

  public void setCompletionScore(@javax.annotation.Nullable BigDecimal completionScore) {
    this.completionScore = completionScore;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationComplianceResponseDto organizationComplianceResponseDto = (OrganizationComplianceResponseDto) o;
    return Objects.equals(this.id, organizationComplianceResponseDto.id) &&
        Objects.equals(this.createdAt, organizationComplianceResponseDto.createdAt) &&
        Objects.equals(this.updatedAt, organizationComplianceResponseDto.updatedAt) &&
        Objects.equals(this.deletedAt, organizationComplianceResponseDto.deletedAt) &&
        Objects.equals(this.organizationId, organizationComplianceResponseDto.organizationId) &&
        Objects.equals(this.companyRegistrationName, organizationComplianceResponseDto.companyRegistrationName) &&
        Objects.equals(this.companyRegistrationNumber, organizationComplianceResponseDto.companyRegistrationNumber) &&
        Objects.equals(this.companyTradingName, organizationComplianceResponseDto.companyTradingName) &&
        Objects.equals(this.vatRegistrationNumber, organizationComplianceResponseDto.vatRegistrationNumber) &&
        Objects.equals(this.industry, organizationComplianceResponseDto.industry) &&
        Objects.equals(this.subIndustry, organizationComplianceResponseDto.subIndustry) &&
        Objects.equals(this.estimatedAnnualTurnover, organizationComplianceResponseDto.estimatedAnnualTurnover) &&
        Objects.equals(this.businessDescription, organizationComplianceResponseDto.businessDescription) &&
        Objects.equals(this.companyMobileMoneySettlementNumber, organizationComplianceResponseDto.companyMobileMoneySettlementNumber) &&
        Objects.equals(this.companyEmail, organizationComplianceResponseDto.companyEmail) &&
        Objects.equals(this.companyContactNumber, organizationComplianceResponseDto.companyContactNumber) &&
        Objects.equals(this.website, organizationComplianceResponseDto.website) &&
        Objects.equals(this.socialMedia, organizationComplianceResponseDto.socialMedia) &&
        Objects.equals(this.accountContactNumber, organizationComplianceResponseDto.accountContactNumber) &&
        Objects.equals(this.customerSupportContactNumber, organizationComplianceResponseDto.customerSupportContactNumber) &&
        Objects.equals(this.customerSupportEscalationContactNumber, organizationComplianceResponseDto.customerSupportEscalationContactNumber) &&
        Objects.equals(this.emergencyContactNumber, organizationComplianceResponseDto.emergencyContactNumber) &&
        Objects.equals(this.streetAddress, organizationComplianceResponseDto.streetAddress) &&
        Objects.equals(this.apartment, organizationComplianceResponseDto.apartment) &&
        Objects.equals(this.suburb, organizationComplianceResponseDto.suburb) &&
        Objects.equals(this.city, organizationComplianceResponseDto.city) &&
        Objects.equals(this.postalCode, organizationComplianceResponseDto.postalCode) &&
        Objects.equals(this.country, organizationComplianceResponseDto.country) &&
        Objects.equals(this.bank, organizationComplianceResponseDto.bank) &&
        Objects.equals(this.accountType, organizationComplianceResponseDto.accountType) &&
        Objects.equals(this.accountName, organizationComplianceResponseDto.accountName) &&
        Objects.equals(this.accountNumber, organizationComplianceResponseDto.accountNumber) &&
        Objects.equals(this.branchCode, organizationComplianceResponseDto.branchCode) &&
        Objects.equals(this.swiftCode, organizationComplianceResponseDto.swiftCode) &&
        Objects.equals(this.certificateOfIncorporation, organizationComplianceResponseDto.certificateOfIncorporation) &&
        Objects.equals(this.identityDocuments, organizationComplianceResponseDto.identityDocuments) &&
        Objects.equals(this.bankAccountConfirmationLetter, organizationComplianceResponseDto.bankAccountConfirmationLetter) &&
        Objects.equals(this.proofOfBusinessAddress, organizationComplianceResponseDto.proofOfBusinessAddress) &&
        Objects.equals(this.termsAccepted, organizationComplianceResponseDto.termsAccepted) &&
        Objects.equals(this.acceptedAt, organizationComplianceResponseDto.acceptedAt) &&
        Objects.equals(this.currentStep, organizationComplianceResponseDto.currentStep) &&
        Objects.equals(this.status, organizationComplianceResponseDto.status) &&
        Objects.equals(this.isCompleted, organizationComplianceResponseDto.isCompleted) &&
        Objects.equals(this.completionScore, organizationComplianceResponseDto.completionScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, deletedAt, organizationId, companyRegistrationName, companyRegistrationNumber, companyTradingName, vatRegistrationNumber, industry, subIndustry, estimatedAnnualTurnover, businessDescription, companyMobileMoneySettlementNumber, companyEmail, companyContactNumber, website, socialMedia, accountContactNumber, customerSupportContactNumber, customerSupportEscalationContactNumber, emergencyContactNumber, streetAddress, apartment, suburb, city, postalCode, country, bank, accountType, accountName, accountNumber, branchCode, swiftCode, certificateOfIncorporation, identityDocuments, bankAccountConfirmationLetter, proofOfBusinessAddress, termsAccepted, acceptedAt, currentStep, status, isCompleted, completionScore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationComplianceResponseDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    companyRegistrationName: ").append(toIndentedString(companyRegistrationName)).append("\n");
    sb.append("    companyRegistrationNumber: ").append(toIndentedString(companyRegistrationNumber)).append("\n");
    sb.append("    companyTradingName: ").append(toIndentedString(companyTradingName)).append("\n");
    sb.append("    vatRegistrationNumber: ").append(toIndentedString(vatRegistrationNumber)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    subIndustry: ").append(toIndentedString(subIndustry)).append("\n");
    sb.append("    estimatedAnnualTurnover: ").append(toIndentedString(estimatedAnnualTurnover)).append("\n");
    sb.append("    businessDescription: ").append(toIndentedString(businessDescription)).append("\n");
    sb.append("    companyMobileMoneySettlementNumber: ").append(toIndentedString(companyMobileMoneySettlementNumber)).append("\n");
    sb.append("    companyEmail: ").append(toIndentedString(companyEmail)).append("\n");
    sb.append("    companyContactNumber: ").append(toIndentedString(companyContactNumber)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    socialMedia: ").append(toIndentedString(socialMedia)).append("\n");
    sb.append("    accountContactNumber: ").append(toIndentedString(accountContactNumber)).append("\n");
    sb.append("    customerSupportContactNumber: ").append(toIndentedString(customerSupportContactNumber)).append("\n");
    sb.append("    customerSupportEscalationContactNumber: ").append(toIndentedString(customerSupportEscalationContactNumber)).append("\n");
    sb.append("    emergencyContactNumber: ").append(toIndentedString(emergencyContactNumber)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    apartment: ").append(toIndentedString(apartment)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    branchCode: ").append(toIndentedString(branchCode)).append("\n");
    sb.append("    swiftCode: ").append(toIndentedString(swiftCode)).append("\n");
    sb.append("    certificateOfIncorporation: ").append(toIndentedString(certificateOfIncorporation)).append("\n");
    sb.append("    identityDocuments: ").append(toIndentedString(identityDocuments)).append("\n");
    sb.append("    bankAccountConfirmationLetter: ").append(toIndentedString(bankAccountConfirmationLetter)).append("\n");
    sb.append("    proofOfBusinessAddress: ").append(toIndentedString(proofOfBusinessAddress)).append("\n");
    sb.append("    termsAccepted: ").append(toIndentedString(termsAccepted)).append("\n");
    sb.append("    acceptedAt: ").append(toIndentedString(acceptedAt)).append("\n");
    sb.append("    currentStep: ").append(toIndentedString(currentStep)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isCompleted: ").append(toIndentedString(isCompleted)).append("\n");
    sb.append("    completionScore: ").append(toIndentedString(completionScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "createdAt", "updatedAt", "deletedAt", "organizationId", "companyRegistrationName", "companyRegistrationNumber", "companyTradingName", "vatRegistrationNumber", "industry", "subIndustry", "estimatedAnnualTurnover", "businessDescription", "companyMobileMoneySettlementNumber", "companyEmail", "companyContactNumber", "website", "socialMedia", "accountContactNumber", "customerSupportContactNumber", "customerSupportEscalationContactNumber", "emergencyContactNumber", "streetAddress", "apartment", "suburb", "city", "postalCode", "country", "bank", "accountType", "accountName", "accountNumber", "branchCode", "swiftCode", "certificateOfIncorporation", "identityDocuments", "bankAccountConfirmationLetter", "proofOfBusinessAddress", "termsAccepted", "acceptedAt", "currentStep", "status", "isCompleted", "completionScore"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "createdAt", "updatedAt", "organizationId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrganizationComplianceResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganizationComplianceResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in OrganizationComplianceResponseDto is not found in the empty JSON string", OrganizationComplianceResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrganizationComplianceResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OrganizationComplianceResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OrganizationComplianceResponseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("organizationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `organizationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organizationId").toString()));
      }
      if ((jsonObj.get("companyRegistrationName") != null && !jsonObj.get("companyRegistrationName").isJsonNull()) && !jsonObj.get("companyRegistrationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyRegistrationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyRegistrationName").toString()));
      }
      if ((jsonObj.get("companyRegistrationNumber") != null && !jsonObj.get("companyRegistrationNumber").isJsonNull()) && !jsonObj.get("companyRegistrationNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyRegistrationNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyRegistrationNumber").toString()));
      }
      if ((jsonObj.get("companyTradingName") != null && !jsonObj.get("companyTradingName").isJsonNull()) && !jsonObj.get("companyTradingName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyTradingName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyTradingName").toString()));
      }
      if ((jsonObj.get("vatRegistrationNumber") != null && !jsonObj.get("vatRegistrationNumber").isJsonNull()) && !jsonObj.get("vatRegistrationNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `vatRegistrationNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vatRegistrationNumber").toString()));
      }
      if ((jsonObj.get("industry") != null && !jsonObj.get("industry").isJsonNull()) && !jsonObj.get("industry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `industry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("industry").toString()));
      }
      if ((jsonObj.get("subIndustry") != null && !jsonObj.get("subIndustry").isJsonNull()) && !jsonObj.get("subIndustry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `subIndustry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subIndustry").toString()));
      }
      if ((jsonObj.get("estimatedAnnualTurnover") != null && !jsonObj.get("estimatedAnnualTurnover").isJsonNull()) && !jsonObj.get("estimatedAnnualTurnover").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `estimatedAnnualTurnover` to be a primitive type in the JSON string but got `%s`", jsonObj.get("estimatedAnnualTurnover").toString()));
      }
      if ((jsonObj.get("businessDescription") != null && !jsonObj.get("businessDescription").isJsonNull()) && !jsonObj.get("businessDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `businessDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessDescription").toString()));
      }
      if ((jsonObj.get("companyMobileMoneySettlementNumber") != null && !jsonObj.get("companyMobileMoneySettlementNumber").isJsonNull()) && !jsonObj.get("companyMobileMoneySettlementNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyMobileMoneySettlementNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyMobileMoneySettlementNumber").toString()));
      }
      if ((jsonObj.get("companyEmail") != null && !jsonObj.get("companyEmail").isJsonNull()) && !jsonObj.get("companyEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyEmail").toString()));
      }
      if ((jsonObj.get("companyContactNumber") != null && !jsonObj.get("companyContactNumber").isJsonNull()) && !jsonObj.get("companyContactNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyContactNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyContactNumber").toString()));
      }
      if ((jsonObj.get("website") != null && !jsonObj.get("website").isJsonNull()) && !jsonObj.get("website").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `website` to be a primitive type in the JSON string but got `%s`", jsonObj.get("website").toString()));
      }
      if ((jsonObj.get("socialMedia") != null && !jsonObj.get("socialMedia").isJsonNull()) && !jsonObj.get("socialMedia").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `socialMedia` to be a primitive type in the JSON string but got `%s`", jsonObj.get("socialMedia").toString()));
      }
      if ((jsonObj.get("accountContactNumber") != null && !jsonObj.get("accountContactNumber").isJsonNull()) && !jsonObj.get("accountContactNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `accountContactNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountContactNumber").toString()));
      }
      if ((jsonObj.get("customerSupportContactNumber") != null && !jsonObj.get("customerSupportContactNumber").isJsonNull()) && !jsonObj.get("customerSupportContactNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `customerSupportContactNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerSupportContactNumber").toString()));
      }
      if ((jsonObj.get("customerSupportEscalationContactNumber") != null && !jsonObj.get("customerSupportEscalationContactNumber").isJsonNull()) && !jsonObj.get("customerSupportEscalationContactNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `customerSupportEscalationContactNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerSupportEscalationContactNumber").toString()));
      }
      if ((jsonObj.get("emergencyContactNumber") != null && !jsonObj.get("emergencyContactNumber").isJsonNull()) && !jsonObj.get("emergencyContactNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `emergencyContactNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emergencyContactNumber").toString()));
      }
      if ((jsonObj.get("streetAddress") != null && !jsonObj.get("streetAddress").isJsonNull()) && !jsonObj.get("streetAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `streetAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("streetAddress").toString()));
      }
      if ((jsonObj.get("apartment") != null && !jsonObj.get("apartment").isJsonNull()) && !jsonObj.get("apartment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `apartment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("apartment").toString()));
      }
      if ((jsonObj.get("suburb") != null && !jsonObj.get("suburb").isJsonNull()) && !jsonObj.get("suburb").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `suburb` to be a primitive type in the JSON string but got `%s`", jsonObj.get("suburb").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("postalCode") != null && !jsonObj.get("postalCode").isJsonNull()) && !jsonObj.get("postalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `postalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postalCode").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if ((jsonObj.get("bank") != null && !jsonObj.get("bank").isJsonNull()) && !jsonObj.get("bank").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `bank` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bank").toString()));
      }
      if ((jsonObj.get("accountType") != null && !jsonObj.get("accountType").isJsonNull()) && !jsonObj.get("accountType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `accountType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountType").toString()));
      }
      if ((jsonObj.get("accountName") != null && !jsonObj.get("accountName").isJsonNull()) && !jsonObj.get("accountName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `accountName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountName").toString()));
      }
      if ((jsonObj.get("accountNumber") != null && !jsonObj.get("accountNumber").isJsonNull()) && !jsonObj.get("accountNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `accountNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountNumber").toString()));
      }
      if ((jsonObj.get("branchCode") != null && !jsonObj.get("branchCode").isJsonNull()) && !jsonObj.get("branchCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `branchCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branchCode").toString()));
      }
      if ((jsonObj.get("swiftCode") != null && !jsonObj.get("swiftCode").isJsonNull()) && !jsonObj.get("swiftCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `swiftCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("swiftCode").toString()));
      }
      if ((jsonObj.get("certificateOfIncorporation") != null && !jsonObj.get("certificateOfIncorporation").isJsonNull()) && !jsonObj.get("certificateOfIncorporation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `certificateOfIncorporation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("certificateOfIncorporation").toString()));
      }
      if ((jsonObj.get("identityDocuments") != null && !jsonObj.get("identityDocuments").isJsonNull()) && !jsonObj.get("identityDocuments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `identityDocuments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identityDocuments").toString()));
      }
      if ((jsonObj.get("bankAccountConfirmationLetter") != null && !jsonObj.get("bankAccountConfirmationLetter").isJsonNull()) && !jsonObj.get("bankAccountConfirmationLetter").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `bankAccountConfirmationLetter` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bankAccountConfirmationLetter").toString()));
      }
      if ((jsonObj.get("proofOfBusinessAddress") != null && !jsonObj.get("proofOfBusinessAddress").isJsonNull()) && !jsonObj.get("proofOfBusinessAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `proofOfBusinessAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("proofOfBusinessAddress").toString()));
      }
      if ((jsonObj.get("currentStep") != null && !jsonObj.get("currentStep").isJsonNull()) && !jsonObj.get("currentStep").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `currentStep` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currentStep").toString()));
      }
      // validate the optional field `currentStep`
      if (jsonObj.get("currentStep") != null && !jsonObj.get("currentStep").isJsonNull()) {
        CurrentStepEnum.validateJsonElement(jsonObj.get("currentStep"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationComplianceResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationComplianceResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationComplianceResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationComplianceResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationComplianceResponseDto>() {
           @Override
           public void write(JsonWriter out, OrganizationComplianceResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationComplianceResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrganizationComplianceResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrganizationComplianceResponseDto
   * @throws IOException if the JSON string is invalid with respect to OrganizationComplianceResponseDto
   */
  public static OrganizationComplianceResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationComplianceResponseDto.class);
  }

  /**
   * Convert an instance of OrganizationComplianceResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

