/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.cashful.JSON;

/**
 * RequestUploadUrlDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RequestUploadUrlDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @SerializedName(SERIALIZED_NAME_FILENAME)
  @javax.annotation.Nonnull
  private String filename;

  public static final String SERIALIZED_NAME_MIME_TYPE = "mimeType";
  @SerializedName(SERIALIZED_NAME_MIME_TYPE)
  @javax.annotation.Nonnull
  private String mimeType;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_RELATED_ENTITY_ID = "relatedEntityId";
  @SerializedName(SERIALIZED_NAME_RELATED_ENTITY_ID)
  @javax.annotation.Nullable
  private String relatedEntityId;

  public static final String SERIALIZED_NAME_RELATED_ENTITY_TYPE = "relatedEntityType";
  @SerializedName(SERIALIZED_NAME_RELATED_ENTITY_TYPE)
  @javax.annotation.Nullable
  private String relatedEntityType;

  public static final String SERIALIZED_NAME_IS_PUBLIC = "isPublic";
  @SerializedName(SERIALIZED_NAME_IS_PUBLIC)
  @javax.annotation.Nullable
  private Boolean isPublic = false;

  public RequestUploadUrlDto() {
  }

  public RequestUploadUrlDto filename(@javax.annotation.Nonnull String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Original filename
   * @return filename
   */
  @javax.annotation.Nonnull
  public String getFilename() {
    return filename;
  }

  public void setFilename(@javax.annotation.Nonnull String filename) {
    this.filename = filename;
  }


  public RequestUploadUrlDto mimeType(@javax.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * MIME type of the file
   * @return mimeType
   */
  @javax.annotation.Nonnull
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(@javax.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
  }


  public RequestUploadUrlDto tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public RequestUploadUrlDto addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Tags for classification
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public RequestUploadUrlDto relatedEntityId(@javax.annotation.Nullable String relatedEntityId) {
    this.relatedEntityId = relatedEntityId;
    return this;
  }

  /**
   * Related entity ID (e.g., compliance info ID)
   * @return relatedEntityId
   */
  @javax.annotation.Nullable
  public String getRelatedEntityId() {
    return relatedEntityId;
  }

  public void setRelatedEntityId(@javax.annotation.Nullable String relatedEntityId) {
    this.relatedEntityId = relatedEntityId;
  }


  public RequestUploadUrlDto relatedEntityType(@javax.annotation.Nullable String relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
    return this;
  }

  /**
   * Related entity type
   * @return relatedEntityType
   */
  @javax.annotation.Nullable
  public String getRelatedEntityType() {
    return relatedEntityType;
  }

  public void setRelatedEntityType(@javax.annotation.Nullable String relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
  }


  public RequestUploadUrlDto isPublic(@javax.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

  /**
   * Whether the file should be publicly accessible
   * @return isPublic
   */
  @javax.annotation.Nullable
  public Boolean getIsPublic() {
    return isPublic;
  }

  public void setIsPublic(@javax.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestUploadUrlDto requestUploadUrlDto = (RequestUploadUrlDto) o;
    return Objects.equals(this.filename, requestUploadUrlDto.filename) &&
        Objects.equals(this.mimeType, requestUploadUrlDto.mimeType) &&
        Objects.equals(this.tags, requestUploadUrlDto.tags) &&
        Objects.equals(this.relatedEntityId, requestUploadUrlDto.relatedEntityId) &&
        Objects.equals(this.relatedEntityType, requestUploadUrlDto.relatedEntityType) &&
        Objects.equals(this.isPublic, requestUploadUrlDto.isPublic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filename, mimeType, tags, relatedEntityId, relatedEntityType, isPublic);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestUploadUrlDto {\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    relatedEntityId: ").append(toIndentedString(relatedEntityId)).append("\n");
    sb.append("    relatedEntityType: ").append(toIndentedString(relatedEntityType)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("filename", "mimeType", "tags", "relatedEntityId", "relatedEntityType", "isPublic"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("filename", "mimeType"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RequestUploadUrlDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RequestUploadUrlDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in RequestUploadUrlDto is not found in the empty JSON string", RequestUploadUrlDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RequestUploadUrlDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RequestUploadUrlDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestUploadUrlDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("filename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `filename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filename").toString()));
      }
      if (!jsonObj.get("mimeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `mimeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mimeType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if ((jsonObj.get("relatedEntityId") != null && !jsonObj.get("relatedEntityId").isJsonNull()) && !jsonObj.get("relatedEntityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `relatedEntityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relatedEntityId").toString()));
      }
      if ((jsonObj.get("relatedEntityType") != null && !jsonObj.get("relatedEntityType").isJsonNull()) && !jsonObj.get("relatedEntityType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `relatedEntityType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relatedEntityType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestUploadUrlDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestUploadUrlDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestUploadUrlDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestUploadUrlDto.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestUploadUrlDto>() {
           @Override
           public void write(JsonWriter out, RequestUploadUrlDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestUploadUrlDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RequestUploadUrlDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RequestUploadUrlDto
   * @throws IOException if the JSON string is invalid with respect to RequestUploadUrlDto
   */
  public static RequestUploadUrlDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestUploadUrlDto.class);
  }

  /**
   * Convert an instance of RequestUploadUrlDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

