/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import com.cashful.model.CustomerStatsDto;
import com.cashful.model.CustomerTransactionDto;
import com.cashful.model.TimeframeMetricsDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AnalyticsResponseDto
 */
public class AnalyticsResponseDtoTest {
    private final AnalyticsResponseDto model = new AnalyticsResponseDto();

    /**
     * Model tests for AnalyticsResponseDto
     */
    @Test
    public void testAnalyticsResponseDto() {
        // TODO: test AnalyticsResponseDto
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'newCustomers'
     */
    @Test
    public void newCustomersTest() {
        // TODO: test newCustomers
    }

    /**
     * Test the property 'recentTransactions'
     */
    @Test
    public void recentTransactionsTest() {
        // TODO: test recentTransactions
    }

}
