/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import com.cashful.model.EvervaultEncryptedCardDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfirmPaymentIntentDto
 */
public class ConfirmPaymentIntentDtoTest {
    private final ConfirmPaymentIntentDto model = new ConfirmPaymentIntentDto();

    /**
     * Model tests for ConfirmPaymentIntentDto
     */
    @Test
    public void testConfirmPaymentIntentDto() {
        // TODO: test ConfirmPaymentIntentDto
    }

    /**
     * Test the property 'evervaultEncryptedCard'
     */
    @Test
    public void evervaultEncryptedCardTest() {
        // TODO: test evervaultEncryptedCard
    }

    /**
     * Test the property 'maskedPan'
     */
    @Test
    public void maskedPanTest() {
        // TODO: test maskedPan
    }

    /**
     * Test the property 'tokenizeCard'
     */
    @Test
    public void tokenizeCardTest() {
        // TODO: test tokenizeCard
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'paymentDescription'
     */
    @Test
    public void paymentDescriptionTest() {
        // TODO: test paymentDescription
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
