/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestPhonePasswordResetDto
 */
public class RequestPhonePasswordResetDtoTest {
    private final RequestPhonePasswordResetDto model = new RequestPhonePasswordResetDto();

    /**
     * Model tests for RequestPhonePasswordResetDto
     */
    @Test
    public void testRequestPhonePasswordResetDto() {
        // TODO: test RequestPhonePasswordResetDto
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'callbackURL'
     */
    @Test
    public void callbackURLTest() {
        // TODO: test callbackURL
    }

}
