/*
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashful.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendMultiChannelNotification200Response
 */
public class SendMultiChannelNotification200ResponseTest {
    private final SendMultiChannelNotification200Response model = new SendMultiChannelNotification200Response();

    /**
     * Model tests for SendMultiChannelNotification200Response
     */
    @Test
    public void testSendMultiChannelNotification200Response() {
        // TODO: test SendMultiChannelNotification200Response
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'sms'
     */
    @Test
    public void smsTest() {
        // TODO: test sms
    }

}
